### ISSUE TITLE
Pagination number should be reset for new result

### ISSUE THREAD

**Issue by baktiaditya** [trybick/issue-collab#13]
<img width="680" alt="Screen Shot 2019-10-07 at 18 00 06" src="https://user-images.githubusercontent.com/2070906/66306770-bcfc6080-e92c-11e9-9508-8e345663bea3.png">

**Comment by trybick** [comment]
Hey @baktiaditya When does this happen? Just want to make sure I understand "reset for new result"

**Comment by trybick** [comment]
Oh, I think it's for when you click "Load Issues" a second time, correct?

**Comment by baktiaditya** [comment]
yup, we need to reset pagination number state every "Load Issues" is clicked, otherwise it will display an empty result (after we traverse using pagination and changing filter)

![PettyHopefulAngora-size_restricted](https://user-images.githubusercontent.com/2070906/66342726-4daa5f00-e974-11e9-974b-e5fc99869e48.gif)
