### ISSUE TITLE
Add a debounce to the Get Issues button

### ISSUE THREAD

**Issue by trybick** [trybick/issue-collab#18]
This is the button that makes the API call to GitHub
https://github.com/trybick/issue-collab/blob/master/src/components/App.jsx#L186

Is it possible to add a debounce without adding external libraries like lodash?

**Comment by andrewfluck** [comment]
Typically you would add debounce to features like search, is there any reason it would be required on a button? Would it be to prevent multiple clicks?

**Comment by andrewfluck** [comment]
A debounce shouldn't be that hard to implement anyway

**Comment by trybick** [comment]
@andrewfluck Yeah the idea would be to prevent multiple clicks. Currently if you rapid click the button it will make an API call every time, which might be good to avoid. Would you agree?

**Comment by andrewfluck** [comment]
Certainly
