### ISSUE TITLE
Add better styling to the results

### ISSUE THREAD

**Issue by trybick** [trybick/issue-collab#2]
The code lives here: 
https://github.com/trybick/issue-collab/blob/master/src/components/search/SearchResults.jsx

**Comment by jmoranin98** [comment]
I would like to collaborate

**Comment by trybick** [comment]
@jmoranin98 Please check out the styling updates in this screenshot in this PR and see if you want to add anything else
https://github.com/trybick/issue-collab/pull/7

Some possibilities: 
-The "Total Results" display
-The repo name / project name section (example: trybick/issue-collab) 
-The Title for each result still has default URL styling

**Comment by jmoranin98** [comment]
Working on it

**Comment by trybick** [comment]
@jmoranin98 Your work looks great!
