### ISSUE TITLE
Fix text going outside designated area

### ISSUE THREAD

**Issue by trybick** [trybick/issue-collab#20]
The description goes off the card to the right. Some type of max-width or truncation could work. 

![Screen Shot 2019-10-07 at 8 36 13 PM](https://user-images.githubusercontent.com/39889198/66358735-30f53380-e942-11e9-90d7-387a778ddcce.png)

code lives here: https://github.com/trybick/issue-collab/blob/master/src/components/search/SearchResult.jsx#L30

**Comment by vrchavez** [comment]
@trybick Claiming this!

**Comment by vrchavez** [comment]
[Made change to paragraph text container. #21](https://github.com/trybick/issue-collab/pull/21)

**Comment by trybick** [comment]
Thanks @vrchavez !
