### ISSUE TITLE
Add styling to the description text

### ISSUE THREAD

**Issue by trybick** [trybick/issue-collab#25]
Each issue's description/body text looks similar to the `username/project-name` part below it. Could we add something to differentiate them more?

![Screen Shot 2019-10-08 at 4 42 34 PM](https://user-images.githubusercontent.com/39889198/66431789-acaabb00-e9ea-11e9-93fc-311b71111e81.png)

Please include a screenshot with the PR 😃 

code: https://github.com/trybick/issue-collab/blob/master/src/components/search/SearchResult.jsx#L30

**Comment by mazma1** [comment]
Hi @trybick, can I help with this?

**Comment by mccarthydanielle** [comment]
I can work on this. Is there any specific design you're interested in or can I implement and get approval?

**Comment by trybick** [comment]
@mazma1 go for it!

@mccarthydanielle there is another styling ticket open if you'd like or you can also feel free to work on this one and we can add parts of each!
