### ISSUE TITLE
Add styling to Welcome Message

### ISSUE THREAD

**Issue by trybick** [trybick/issue-collab#26]
The welcome message looks a little plain. 

![Screen Shot 2019-10-08 at 4 46 33 PM](https://user-images.githubusercontent.com/39889198/66432065-3bb7d300-e9eb-11e9-8e1a-8aa82a227d06.png)

Some ideas:

- Add a max-width to make the text not extend so far horizontally 
- Move the top line into the header up top
- Make the text visually appealing (font, color, size)

The code lives here: https://github.com/trybick/issue-collab/blob/master/src/components/statuses/InitialGreeting.jsx

Please include a screenshot in your PR 😃

**Comment by galvc** [comment]
Hi can I work on this?

**Comment by trybick** [comment]
@galvc Sure go for it

**Comment by petercr** [comment]
@trybick Hello 👋  if Galvc is working on this issue, maybe you can assign it to them 😄 
Otherwise let me know I'd love to help

**Comment by galvc** [comment]
> Move the top line into the header up top

Did you mean to move the "Find open source projects..." under the Issue Collab title?

**Comment by trybick** [comment]
@galvc Yes exactly

@petercr Thanks for your interest. Feel free to make any suggestions/create an issue. I'll be opening more issues soon too

**Comment by trybick** [comment]
Thank you @galvc - merged to master
