### ISSUE TITLE
Make the body text a clickable link

### ISSUE THREAD

**Issue by trybick** [trybick/issue-collab#28]
Currently the title is a link to the issue. It might be cool to have the body text clickable too for the link. Might have to remove the default blue underline text that gets added to links to keep the formatting the same.

code: https://github.com/trybick/issue-collab/blob/master/src/components/search/SearchResult.jsx#L30

**Comment by renesansz** [comment]
I'll be glad to help with this, I'm looking into it now.

**Comment by hotdang-ca** [comment]
PR Incoming

**Comment by trybick** [comment]
TY guys
