### ISSUE TITLE
Add a better color scheme/change colors for various elements

### ISSUE THREAD

**Issue by trybick** [trybick/issue-collab#36]
It would be great to have a better unified color theme throughout the app, including these elements and anything else you see fit:

- Body background color
- Header text
- Header border
- Buttons

**Comment by Exoceus** [comment]
Ill work on this! Any specific colour scheme(s) in mind? I was thinking of this colour palette to sort of gol along with the current blue accent color: https://coolors.co/export/png/ffffff-38aecc-0090c1-046e8f-183446

**Comment by trybick** [comment]
That color theme looks perfect!

**Comment by Exoceus** [comment]
I have created a PR request
