### ISSUE TITLE
Style the app as you see fit 

### ISSUE THREAD

**Issue by trybick** [trybick/issue-collab#38]
Make styling adjustments/improvements that you think the site needs. 

The site is single page web app built in React which you can view here. It should be easy to jump in and start working with the Readme steps.
[https://issue-collab.dev/](https://issue-collab.dev/)

### Please target the master branch for PRs

**Comment by arnxv0** [comment]
I would like to work on this :)

**Comment by trybick** [comment]
@arnxv0 Go for it :) Will keep this issue open to anyone because this can be worked on by multiple people.

**Comment by arnxv0** [comment]
@trybick I have created a pull request, check it out :)

**Comment by palakg01** [comment]
Hey can i work on this?

**Comment by deniswold** [comment]
I am on it if it is still open.

**Comment by trybick** [comment]
@palakg01 @damewold Yes, anyone (and multiple people) can!

**Comment by trybick** [comment]
One PR has been merged that changed to dark theme. If you are already started work without these changes, please attach a screenshot here for your current work.

**Comment by deniswold** [comment]
<img width="1015" alt="Screen Shot 2020-10-03 at 12 16 04 PM" src="https://user-images.githubusercontent.com/57334409/94997686-5ecf8100-0572-11eb-9c42-5b49d0f6af17.png">
<img width="970" alt="Screen Shot 2020-10-03 at 12 16 19 PM" src="https://user-images.githubusercontent.com/57334409/94997689-60994480-0572-11eb-8cf6-f912d2d08881.png">

So far this is how it looks. I am not done yet and I am going to keep working on it.
