### ISSUE TITLE
Error in readme.md

### ISSUE THREAD

**Issue by mRuggi** [trybick/issue-collab#42]
Actually the number of PR to get the T-shirt in hacktoberfest 2020 is 4 but i can't make a pull request only for that error (it feels like cheating and i have already 6 PR in reviewing period), could you fix it? Also if you want i could create Readme-IT.md translating your project docs in italian to make it more accessible.

**Comment by trybick** [comment]
Hey @mRuggi thanks for pointing that out. Sure if you want to make a translation that would be great!!

**Comment by mRuggi** [comment]
Done with #43
