### ISSUE TITLE
Add styling improvements 

### ISSUE THREAD

**Issue by trybick** [trybick/issue-collab#45]
Tweak the styling (we use .scss files) for anywhere you think could use it.

**Comment by TicTak21** [comment]
Hi, @trybick.
I fixed spacing in some blocks. Now the application looks better on mobile devices. Can you check my pull request?

Also, if you are interested, I can translate README into Russian. But I think it's a topic for a separate issue.

**Comment by trybick** [comment]
@TicTak21 I have created issue #49 for translations if you are interested :)

**Comment by trybick** [comment]
**This issue is still open to other styling tweaks people may want to do to the app**
