### ISSUE TITLE
Translate Readme to different languages

### ISSUE THREAD

**Issue by trybick** [trybick/issue-collab#49]
@TicTak21 may be interested in doing Russian. **Anyone else can open a PR to add more translations**. 

Languages already done:
- Italian
- Russian
- French

**Comment by Nopraz** [comment]
I can do french if you want :)

**Comment by wojciechwachowiak** [comment]
Can you assign this to me? I could add polish translation.

**Comment by larissavarjao** [comment]
I could do in portuguese too! :)

**Comment by Nopraz** [comment]
Oops didn't saw that someone already did the readme in french

**Comment by trybick** [comment]
@wojciechwachowiak Polish would be great! I won't be assigning this to one person because it is open to multiple people/multiple languages.

**Comment by amritanshusikdar** [comment]
I can add German 😄

**Comment by TiagoSansao** [comment]
I finished the Brazilian-Portuguese translation ^^
The project's goal is very helpful, congratulations for the idea @trybick  😃

**Comment by im-adithya** [comment]
I can add Hindi translation 😄

**Comment by arifsetyo21** [comment]
i can add indonesian translation

**Comment by panvicka** [comment]
Going to add Czech. I love the project!

**Comment by trybick** [comment]
@panvicka awesome, thank you!

**Comment by Anca07** [comment]
I can add Romanian :)

**Comment by TiagoSansao** [comment]
@trybick I made in Portuguese right now, sorry about before, I'm new in Git :D

**Comment by phast184** [comment]
Hi, I can help translate into Vietnamese. Is this issue still open?
