### ISSUE TITLE
Style and move the dark mode button

### ISSUE THREAD

**Issue by trybick** [trybick/issue-collab#53]
We'd like to:

- Change the current toggle button a dark mode toggle button that looks like [this](https://www.npmjs.com/package/react-dark-mode-toggle) (can use this package or any other method you find as long as the result is a dark mode button that looks like that)
- Move the position of the button so it's next to the GitHub icon on the right

Currently it looks like this:
<img width="867" alt="Screen Shot 2020-10-17 at 7 45 36 AM" src="https://user-images.githubusercontent.com/39889198/96336373-4c167b00-104d-11eb-9ce5-fdd7f7b3e448.png">

**Comment by pranshumaheshwari** [comment]
I can work on it

**Comment by jackson541** [comment]
Hello, i fix this in PR #60
