### ISSUE TITLE
Make dark mode setting persistent with localStorage

### ISSUE THREAD

**Issue by trybick** [trybick/issue-collab#54]
Dark mode was recently implemented here
https://github.com/trybick/issue-collab/blob/master/src/components/App.jsx#L152

If you enable dark mode and refresh the page, the page will be in light mode since the setting is stored in local state. This issue should add the setting to localStorage so the setting is persistent.

**Comment by Nopraz** [comment]
Hi again ! I can add it if you want

**Comment by Nopraz** [comment]
Just did the PR #56
