### ISSUE TITLE
Add number of comments to each search result

### ISSUE THREAD

**Issue by Nopraz** [trybick/issue-collab#57]
It would be a good idea to show the number of comments in issues

**Comment by trybick** [comment]
Thanks for the idea - I like it 👍 

So this issue is open to anyone and we should:
- Fetch the number of comments (start by seeing if `getIssues` in `App.tsx` returns this data already)
- Add the number of comments to the `SearchResult` component. It can be right-aligned.

**Comment by tianlangwu** [comment]
I would like to work on this :)

**Comment by tianlangwu** [comment]
Is this look ok to you? 
![SS02](https://user-images.githubusercontent.com/60892464/96350813-91ef3580-1085-11eb-9318-27866be91322.jpg)

**Comment by trybick** [comment]
@tianlangwu Yes it looks great!
