### ISSUE TITLE
Page not reloading after clicking next on pagination

### ISSUE THREAD

**Issue by itsvvishnu** [trybick/issue-collab#71]
When I load new issues by clicking "find issues" then go to next pages and come back and click "find issues" again the data is not fetched at the first click, or the page is not refreshed at the first click. when i click twice, it works properly

**Comment by trybick** [comment]
Hey @itsvvishnu the Get Issues button is disabled for a few seconds when getIssues is called and getIssues is called when the page changes (handlePageChange). It's designed to prevent users from clicking the button too fast and making too many requests. If you have any ideas how to improve it, let me know! (or feel free to open a PR).

(might also be isButtonLocked that's causing it)
https://github.com/trybick/issue-collab/blob/master/src/components/App.jsx#L235

**Comment by itsvvishnu** [comment]
I waited for the button to become active again then pressed it, but the page didn't refresh,

**Comment by trybick** [comment]
Could you share a video clip/gif?

**Comment by tianlangwu** [comment]
When I click the "find Issue" on the second page, it will still return the same page at the first click, but the second click would work.
![2020-10-20-12-42-02](https://user-images.githubusercontent.com/60892464/96617934-3e255c00-12d2-11eb-8375-9b029be41bfa.gif)

**Comment by trybick** [comment]
Ah I see. So to reproduce:
- Click Find Issues
- Scroll to bottom of page and click Next page
- Click Find Issues again (observe it doesn't work)
- Click Find Issues a second time (observe it loads the first page)

If anyone wants to take a look at making a PR, let me know and we can assign this to you. We might want to consider the desired behavior - maybe clicking Find Issues on the second page should reset everything first and go back to normal behavior of loading page 1.

**Comment by tianlangwu** [comment]
I would like to work on this. Could you please assign it to me?
