### ISSUE TITLE
UI design | front-end part

### ISSUE THREAD

**Issue by thevishalhanda2** [trybick/issue-collab#78]
Hii trybick Can I design and code a frontend UI for this repository/project.

**Comment by trybick** [comment]
Hi, sure. Can you post the designs/what you have in mind here before coding?

**Comment by thevishalhanda2** [comment]
Ok tim

**Comment by thevishalhanda2** [comment]
Hey trybick can we connect on LinkedIn I send you a request of connection on LinkedIn. I've some query related to UI
