### ISSUE TITLE
Change card title to white while in dark mode

### ISSUE THREAD

**Issue by trybick** [trybick/issue-collab#80]
While in dark mode, the card title is hard to read. Change the title to white while in dark mode.
<img width="801" alt="Screen Shot 2021-10-03 at 12 45 29 PM" src="https://user-images.githubusercontent.com/39889198/135763496-70ad2cec-dfb8-4d95-a280-32e615dac458.png">

### How to:
Pass a prop to SearchResults like is being done here
https://github.com/trybick/issue-collab/blob/2961e70dec81c0c0230e036f9b567c8b72bd008b/src/components/App.jsx#L219

Then add `color: white` to `link-title` under the dark mode section here 
https://github.com/trybick/issue-collab/blob/master/src/components/search/SearchResult.scss#L62

**Comment by jennypoon** [comment]
I would like to give this a try

**Comment by kushalShukla-web** [comment]
i wanna work on this issue !!! "__"
